
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVI EOL MULT NUME PAR_DER PAR_IZQ RESTA SUMA\n    s : e EOL\n    \n    e : e SUMA t\n        | e RESTA t\n    \n    e : t\n    \n    t : t MULT f\n        | t DIVI f\n    \n    t : f\n    \n    f : PAR_IZQ e PAR_DER\n    \n    f : NUME\n    '
    
_lr_action_items = {'PAR_IZQ':([0,5,8,9,10,11,],[5,5,5,5,5,5,]),'NUME':([0,5,8,9,10,11,],[6,6,6,6,6,6,]),'$end':([1,7,],[0,-1,]),'EOL':([2,3,4,6,13,14,15,16,17,],[7,-4,-7,-9,-2,-3,-5,-6,-8,]),'SUMA':([2,3,4,6,12,13,14,15,16,17,],[8,-4,-7,-9,8,-2,-3,-5,-6,-8,]),'RESTA':([2,3,4,6,12,13,14,15,16,17,],[9,-4,-7,-9,9,-2,-3,-5,-6,-8,]),'PAR_DER':([3,4,6,12,13,14,15,16,17,],[-4,-7,-9,17,-2,-3,-5,-6,-8,]),'MULT':([3,4,6,13,14,15,16,17,],[10,-7,-9,10,10,-5,-6,-8,]),'DIVI':([3,4,6,13,14,15,16,17,],[11,-7,-9,11,11,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s':([0,],[1,]),'e':([0,5,],[2,12,]),'t':([0,5,8,9,],[3,3,13,14,]),'f':([0,5,8,9,10,11,],[4,4,4,4,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> s","S'",1,None,None,None),
  ('s -> e EOL','s',2,'p_s','interprete.py',30),
  ('e -> e SUMA t','e',3,'p_e1','interprete.py',38),
  ('e -> e RESTA t','e',3,'p_e1','interprete.py',39),
  ('e -> t','e',1,'p_e2','interprete.py',49),
  ('t -> t MULT f','t',3,'p_t1','interprete.py',56),
  ('t -> t DIVI f','t',3,'p_t1','interprete.py',57),
  ('t -> f','t',1,'p_t2','interprete.py',67),
  ('f -> PAR_IZQ e PAR_DER','f',3,'p_f1','interprete.py',74),
  ('f -> NUME','f',1,'p_f2','interprete.py',81),
]
